# The config recipe.
recipe: default.v1

# The assistant project unique identifier
assistant_id: 20240926-000006-dynamic-plot

# Configuration for Rasa NLU.
language: en

# Configuration for Rasa NLU pipeline.
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "bert-base-uncased"
  - name: DIETClassifier
    epochs: 50
# Configuration for Rasa Core.
policies:
- name: RulePolicy
- name: TEDPolicy
  max_history: 5
  epochs: 50
- name: MemoizationPolicy
